/*// Meetings
export const SET_SEARCHED_MEETINGS = 'SET_SEARCHED_MEETINGS'
export const ADD_MEETING = 'ADD_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const STOP_MEETING = 'STOP_MEETING'
export const SAVE_MEETING = 'SAVE_MEETING'
export const CLEAR_MEETINGS = 'CLEAR_MEETINGS'


// Settings
export const SAVE_SETTINGS = 'SAVE_SETTINGS'*/

export const types = {
  SET_SEARCHED_MEETINGS: 	'SET_SEARCHED_MEETINGS',
  GO_TO_MEETING: 					'GO_TO_MEETING',
	ADD_MEETING: 						'ADD_MEETING',
	ADD_ACTIVITY: 					'ADD_ACTIVITY',
	ADD_CALL: 							'ADD_CALL',
	START_MEETING: 					'START_MEETING',
	UPDATE_RATE: 						'UPDATE_RATE',
	STOP_MEETING: 					'STOP_MEETING',
	REMOVE_MEETING:  				'REMOVE_MEETING',
	SAVE_MEETING: 					'SAVE_MEETING',
	CLEAR_MEETINGS: 				'CLEAR_MEETINGS',
	SAVE_SETTINGS: 					'SAVE_SETTINGS',
	ADD_CONTACT: 						'ADD_CONTACT',
	ADD_PARTECIPANT: 				'ADD_PARTECIPANT',
	SET_DATES: 							'SET_DATES',
	SET_SEARCH_KEY: 				'SET_SEARCH_KEY',
	ADD_EVENT: 							'ADD_EVENT',
	ADD_TEMP_CONTACT: 			'ADD_TEMP_CONTACT',
	SAVE_CONTACT_LIST: 			'SAVE_CONTACT_LIST',
}
