/*// Meetings
export const SET_SEARCHED_MEETINGS = 'SET_SEARCHED_MEETINGS'
export const ADD_MEETING = 'ADD_MEETING'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const STOP_MEETING = 'STOP_MEETING'
export const SAVE_MEETING = 'SAVE_MEETING'
export const CLEAR_MEETINGS = 'CLEAR_MEETINGS'


// Settings
export const SAVE_SETTINGS = 'SAVE_SETTINGS'*/

export const types = {
  SET_SEARCHED_MEETINGS: 	'SET_SEARCHED_MEETINGS',
	ADD_MEETING: 						'ADD_MEETING',
	ADD_CALL: 							'ADD_CALL',
	UPDATE_MEETING: 				'UPDATE_MEETING',
	STOP_MEETING: 					'STOP_MEETING',
	SAVE_MEETING: 					'SAVE_MEETING',
	CLEAR_MEETINGS: 				'CLEAR_MEETINGS',
	SAVE_SETTINGS: 					'SAVE_SETTINGS',
	ADD_CONTACT: 						'ADD_CONTACT',
	SET_DATES: 							'SET_DATES',
}
